# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wild Rift Gold Efficiency
description: >- # this means to ignore newlines until "baseurl:"
  WR(Wild Rift) Gold Efficiency, a website combining the gold efficiency calculation formula from 'Gold efficiency (Wild Rift) | League of Legends Wiki' with the design elements from 'WR Meta', featuring manually updated item data from 'Wild Rift'.
baseurl: "/wildrift-gold-efficiency" # the subpath of your site, e.g. /blog
url: "https://changchiyou.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/favicon512x512.png


author:
  name: changchiyou
  url: https://github.com/changchiyou
github_username: changchiyou
google_analytics: "G-3L01ZGR9QJ"

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  # - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

languages: ["en-us", "zh-tw"]
default_lang: "en-us"
languageNames:
  en-us: the U.S. version of English
  zh-tw: Taiwanese Mandarin

feed:
  posts_limit: 10
  path: /feed.xml

# Build settings
# remote_theme: jekyll/minima
# minima:
#   skin: dark
theme: minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include: ["_pages", "images"]
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
  - data.py
  - requirements.txt
  - vendor
  - .trunk/
  - LICENSE
  - docs/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/**/*.{ico,jpg,jpeg,png,svg}"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"
